version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tectonic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
        DATABASE_URL: postgresql://postgres:postgres@db:5432/tectonic
    depends_on:
      - db

  adminer:
      image: adminer
      restart: always
      ports:
          - 5433:8080

volumes:
  postgres_data:
