### Create guild

POST {{base_url}}/api/v1/guilds HTTP/1.1
Authorization: {{api_key}}
Content-Type: application/json

{
  "guild_id": "{{guild_id}}"
}


### Get guild

GET {{base_url}}/api/v1/guilds/{{guild_id}} HTTP/1.1
Authorization: {{api_key}}


### Update guild (full example)

PUT {{base_url}}/api/v1/guilds/{{guild_id}} HTTP/1.1
Authorization: {{api_key}}
Content-Type: application/json

{
  "mod_channel_id": "894970423282892852",
  "multiplier": 2,
  "pb_update": {
    "category_messages": [
      {
        "category": "gwd",
        "message_id": "123456789012345678"
      }
    ],
    "channel_id": "894970423282892852"
  }
}


### Set mod channel only

PUT {{base_url}}/api/v1/guilds/{{guild_id}} HTTP/1.1
Authorization: {{api_key}}
Content-Type: application/json

{
  "mod_channel_id": "123456789012345678"
}


### Set multiplier only

PUT {{base_url}}/api/v1/guilds/{{guild_id}} HTTP/1.1
Authorization: {{api_key}}
Content-Type: application/json

{
  "multiplier": 2
}


### Delete guild

DELETE {{base_url}}/api/v1/guilds/{{guild_id}} HTTP/1.1
Authorization: {{api_key}}


### Get leaderboard

GET {{base_url}}/api/v1/guilds/{{guild_id}}/leaderboard HTTP/1.1
Authorization: {{api_key}}


### Get point sources

GET {{base_url}}/api/v1/guilds/{{guild_id}}/points HTTP/1.1
Authorization: {{api_key}}
