// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Boss struct {
	Name        string `json:"name"`
	DisplayName string `json:"display_name"`
	Category    string `json:"category"`
	Solo        bool   `json:"solo"`
}

type Category struct {
	Thumbnail pgtype.Text `json:"thumbnail"`
	Order     int16       `json:"order"`
	Name      string      `json:"name"`
}

type DetailedTime struct {
	Time        int32            `json:"time"`
	DisplayName pgtype.Text      `json:"display_name"`
	Category    pgtype.Text      `json:"category"`
	RunID       int32            `json:"run_id"`
	Date        pgtype.Timestamp `json:"date"`
	Team        interface{}      `json:"team"`
}

type DetailedTimeTeam struct {
	RunID   int32       `json:"run_id"`
	UserID  string      `json:"user_id"`
	GuildID string      `json:"guild_id"`
	Points  int32       `json:"points"`
	Rsns    interface{} `json:"rsns"`
}

type DetailedUser struct {
	UserID  string      `json:"user_id"`
	GuildID string      `json:"guild_id"`
	Points  int32       `json:"points"`
	Rsns    interface{} `json:"rsns"`
}

type Guild struct {
	GuildID     string      `json:"guild_id"`
	Multiplier  int32       `json:"multiplier"`
	PbChannelID pgtype.Text `json:"pb_channel_id"`
}

type GuildBoss struct {
	Boss    string      `json:"boss"`
	GuildID string      `json:"guild_id"`
	PbID    pgtype.Int4 `json:"pb_id"`
}

type GuildCategory struct {
	GuildID   string      `json:"guild_id"`
	Category  string      `json:"category"`
	MessageID pgtype.Text `json:"message_id"`
}

type PointSource struct {
	GuildID string `json:"guild_id"`
	Source  string `json:"source"`
	Points  int32  `json:"points"`
}

type Rsn struct {
	Rsn     string `json:"rsn"`
	WomID   string `json:"wom_id"`
	UserID  string `json:"user_id"`
	GuildID string `json:"guild_id"`
}

type Team struct {
	RunID   int32  `json:"run_id"`
	UserID  string `json:"user_id"`
	GuildID string `json:"guild_id"`
}

type Time struct {
	Time     int32            `json:"time"`
	BossName string           `json:"boss_name"`
	RunID    int32            `json:"run_id"`
	Date     pgtype.Timestamp `json:"date"`
	GuildID  string           `json:"guild_id"`
}

type User struct {
	UserID  string `json:"user_id"`
	GuildID string `json:"guild_id"`
	Points  int32  `json:"points"`
}
